TaskTrooper/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('app/', include('core.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='home'),
    path('myprojects/', views.myprojects, name='myprojects'), # Overview of all projects
    path('myprojects/addproject', views.addproject, name='addproject'), # Add a project
    path('myprojects/<int:project_id>/', views.project, name='project'), # Overview of a project
    path('myprojects/<int:project_id>/deleteproject', views.deleteproject, name='deleteproject'), # Delete a project
    path('myprojects/<int:project_id>/usermanagement/', views.user_management, name='user_management'), # Bulk modify users' permissions
    path('myprojects/<int:project_id>/projectmanagement/', views.project_management, name='project_management'), # Manage a project
    path('myprojects/<int:project_id>/updateprojectname/', views.update_project_name, name='updateprojectname'),
    path('myprojects/<int:project_id>/edituserprofile/', views.edit_user_profile, name='edituserprofile'),
    path('myprojects/<int:project_id>/allusers/', views.allusers, name='allusers'),
    path('myprojects/<str:invite_code>/join', views.joinproject, name='joinproject'), # Join a project
    path('myprojects/<int:project_id>/addtask', views.addtask, name='addtask'), # Add a task
    path('myprojects/<int:project_id>/<int:task_id>/', views.taskproperties, name='taskproperties'), # Overview of a task
    path('myprojects/<int:project_id>/<int:task_id>/deletetask', views.deletetask, name='deletetask'), # Delete a task
    path('myprojects/<int:project_id>/<int:task_id>/changetaskstatus', views.changetaskstatus, name='changetaskstatus'), # Change a task's status
    path('myprojects/<int:project_id>/<int:task_id>/modifytask', views.modifytask, name='modifytask') # Change a task's status
]

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from django.db import transaction
from django.http import HttpResponseRedirect
import os

from .models import Project, Task, ProjectPermission, UserProfile, File
from .forms import AddTaskForm, AddProjectForm, ChangeTaskStatusForm, BulkModifyPermissionForm, BulkRemoveUserForm, ModifyTaskForm, UserProfileForm

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    return render(request, "core/index.html")

def myprojects(request):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    created_projects = request.user.created_projects.all()
    joined_projects = request.user.joined_projects.exclude(creator=request.user)

    return render(request, "core/myprojects.html", {
        "created_projects": created_projects,
        "joined_projects": joined_projects
    })

def project(request, project_id):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    project = Project.objects.get(id=project_id)
    tasks = project.tasks.all()

    return render(request, "core/project.html", {
        "project": project,
        "tasks": tasks,
    })

def addproject(request):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    creator = request.user
    if request.method == "POST":
        form = AddProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.creator = creator
            project.save()
            return redirect(reverse("core:myprojects"))

    else:
        form = AddProjectForm()

    return render(request, "core/addproject.html", {
        "form":form,
    })

def deleteproject(request, project_id):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    project = get_object_or_404(Project, id=project_id)

    if request.method == "POST":
        project.delete_project()
        return redirect(reverse("core:myprojects"))
    
    return render(request, "core/deleteproject.html", {
        "project":project
    })

def joinproject(request, invite_code):
    if not request.user.is_authenticated:
        return redirect(reverse("account_login"))
    
    project = get_object_or_404(Project, invite_code=invite_code)
    user = request.user
    project.addUser(user)
    return redirect('core:project', project_id=project.id)

def edit_user_profile(request, project_id):
    if not request.user.is_authenticated:
        return redirect(reverse("account_login"))
    
    project = Project.objects.get(id=project_id)
    user_profile = get_object_or_404(UserProfile, user=request.user, project_id=project_id)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('core:project', project_id=project_id)
    else:
        form = UserProfileForm(instance=user_profile)

    context = {
        'form': form,
        'user_profile': user_profile,
        "project": project,
    }

    return render(request, 'core/edit_user_profile.html', context)

def allusers(request, project_id):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    project = Project.objects.get(id=project_id)
    users = project.users.all()

    return render(request, "core/allusers.html", {
        "project": project,
        "users": users,
    })

def addtask(request, project_id):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    project = Project.objects.get(id=project_id)
    if request.method == "POST":
        form = AddTaskForm(project_id, request.POST, request.FILES)  # Include request.FILES for file uploads
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project
            task.save()

            # Associate selected users with the task
            selected_users = form.cleaned_data['users']
            task.users.set(selected_users)

            # Handle multiple files
            new_files = request.FILES.getlist('new_files')
            for uploaded_file in new_files:
                file_instance = File(file=uploaded_file, project=project, task=task)
                file_instance.save()

            # Save the task with associated users and files
            form.save_m2m()

            return redirect(reverse("core:project", args=(project.id,)))

    else:
        form = AddTaskForm(project_id)

    return render(request, "core/addtask.html", {
        "form": form,
        "project": project
    })

def taskproperties(request, project_id, task_id):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    project = Project.objects.get(id=project_id)
    task = Task.objects.get(id=task_id)
    return render(request, "core/taskproperties.html", {
        "project": project,
        "task": task
    })

def changetaskstatus(request, project_id, task_id):
    project = Project.objects.get(id=project_id)
    task = Task.objects.get(id=task_id)
    if request.method == "POST":
        form = ChangeTaskStatusForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect(reverse("core:project", args=(project_id,)))
    else:
        form = ChangeTaskStatusForm(instance=task)

    return render(request, "core/changetaskstatus.html", {
        "project": project,
        "form": form,
        "task": task
    })

def modifytask(request, project_id, task_id):
    task = get_object_or_404(Task, id=task_id, project_id=project_id)
    project = task.project

    if request.method == "POST":
        form = ModifyTaskForm(request.POST, request.FILES, instance=task, project=project)
        if form.is_valid():
            task = form.save()
            
            files_to_delete = form.cleaned_data['files_to_delete']

            if files_to_delete:
                # return render(request, 'core/confirm_file_deletion.html', {
                #     'files_to_delete': files_to_delete,
                #     'project': project
                # })
                for file in files_to_delete:
                    file.delete()
                return redirect(reverse("core:project", args=(project_id,)))

            files = request.FILES.getlist('new_files')
            for file in files:
                File.objects.create(task=task, file=file)

            return redirect(reverse("core:project", args=(project_id,)))
    else:
        form = ModifyTaskForm(instance=task, project=project)

    return render(request, 'core/modifytask.html', {
        'form': form,
        'project': project,
        'task': task
    })

def deletetask(request, project_id, task_id):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    project = get_object_or_404(Project, id=project_id)
    task = get_object_or_404(Task, id=task_id)

    if request.method == "POST":
        task.delete_task()
        return redirect(reverse("core:project", args=(project.id,)))
    
    return render(request, "core/deletetask.html", {
        "project":project,
        "task":task
    })

def user_management(request, project_id):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))

    project = get_object_or_404(Project, id=project_id)
    project_permission = ProjectPermission.objects.filter(project=project, user=request.user).first()
    users = project.users.all()

    if request.method == "POST":
        form_modify_permissions = BulkModifyPermissionForm(request.POST, project=project, request=request)
        form_delete_users = BulkRemoveUserForm(request.POST, project=project, request=request)

        if form_modify_permissions.is_valid():
            new_permission = form_modify_permissions.cleaned_data['new_permission']
            selected_users = form_modify_permissions.cleaned_data['selected_users']

            for user_id in selected_users:
                user = User.objects.get(id=user_id)
                project.updatePermission(user, new_permission)

            messages.success(request, "Permissions updated successfully.")
            return redirect('core:project', project_id=project.id)
        
        if form_delete_users.is_valid():
            selected_users = form_delete_users.cleaned_data['selected_users']

            for user_id in selected_users:
                user = User.objects.get(id=user_id)
                project.removeUser(user)

            messages.success(request, "Users removed successfully.")
            return redirect('core:project', project_id=project.id)
    else:
        form_modify_permissions = BulkModifyPermissionForm(project=project, request=request)
        form_delete_users = BulkRemoveUserForm(project=project, request=request)

    return render(request, "core/usermanagement.html", {
        "project": project,
        "users": users,
        "form_modify_permissions": form_modify_permissions,
        "form_delete_users": form_delete_users,
    })

def project_management(request, project_id):
    if not request.user.is_authenticated:
        return redirect(reverse("main:home"))
    
    project = get_object_or_404(Project, id=project_id)

    if not ProjectPermission.objects.filter(project=project, user=request.user).first().has_permission('delete_project'):
        return redirect(reverse("core:project", args=(project.id,)))
                        
    return render(request, "core/projectmanagement.html", {
        "project": project,
    })

def update_project_name(request, project_id):
    if not request.user.is_authenticated:

core/templates/core/addproject.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}
    {{ project.name }}
{% endblock %}

{% load crispy_forms_tags %}

{% block body %}
  <!-- Navbar -->
  {% include "core/navbarlayout.html" %}

  <!-- Welcome -->
  <section class="bg-dark-blue-2 text-light text-center text-sm-start p-5 p-lg-0 pt-lg-5" style="height: 100vh;">
    <div class="container py-5">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Add Project</button>
      </form>
    </div>
  </section>
{% endblock %}

core/templates/core/allusers.html
{% extends "main/layout.html" %}
{% load permissions_tags %}
{% load static %}

{% block title %}
  {{ project.name }} 
{% endblock %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}">
{% endblock %}

{% block body %}

  <!-- Loads and stores the permissions the user has -->
  {% has_permission user "read" project.id as user_has_read_permission %}
  {% has_permission user "add_users" project.id as user_has_add_users_permission %}
  {% has_permission user "create_tasks" project.id as user_has_create_tasks_permission %}
  {% has_permission user "modify_tasks" project.id as user_has_modify_tasks_permission %}
  {% has_permission user "delete_tasks" project.id as user_has_delete_tasks_permission %}
  {% has_permission user "modify_other_users_permissions" project.id as user_has_modify_other_users_permissions %}
  {% has_permission user "delete_users" project.id as user_has_delete_users_permission %}
  {% has_permission user "delete_project" project.id as user_has_delete_project_permission %}
  {% has_permission user "creator" project.id as user_has_creator_permission %}

  {% include "core/navbarlayout.html" %}
  {% include "core/sidebarlayout.html" with user_has_modify_other_users_permissions=user_has_modify_other_users_permissions user_has_delete_project_permission=user_has_delete_project_permission %}

  <section class="bg-dark-blue-2 text-light text-center p-5 p-lg-0 pt-lg-5" style="min-height: 100vh; display: flex; align-items: top;">
    <div class="container">
        <table class="table text-light" data-toggle="table">
          {% if users %}
          <thead>
            <tr>
              <th scope="col">id</th>
              <th scope="col">Username</th>
              <th data-sortable="true" scope="col">Permission</th>
              <th data-sortable="true" scope="col">Permission Level</th>
              <th scope="col">Display Name</th>
              <th scope="col">Role</th>
              <th scope="col">Phone Number</th>
              <th scope="col">Email Address</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ user.username }}</td>
                <td>
                  {% get_project_permission user project as project_permission %}
                  {{ project_permission }}
                </td>
                <td>
                  {% get_project_permission_level user project as project_permission_level %}
                  {{ project_permission_level }}
                </td>
                <td>
                  {% get_user_profile user project as user_profile %}
                  {{ user_profile.display_name|default:"-" }}
                </td>
                <td>
                  {% get_user_profile user project as user_profile %}
                  {{ user_profile.role|default:"-" }}
                </td>
                <td>
                  {% get_user_profile user project as user_profile %}
                  {{ user_profile.phone_number|default:"-" }}
                </td>
                <td>
                  {% get_user_profile user project as user_profile %}
                  {{ user_profile.email_address|default:"-" }}
                </td>
              </tr>
            {% endfor %}
          </tbody>
          {% else %}
            <tr>
              <td colspan="6">No users found.</td>
            </tr>
          {% endif %}
        </table>
      </div>
  </section>
  
{% endblock %}

core/templates/core/changetaskstatus.html
{% extends "main/layout.html" %}
{% load permissions_tags %}
{% load static %}

{% block title %}
    {{ project.name }}
{% endblock %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}">
{% endblock %}

{% load crispy_forms_tags %}

{% block body %}
  <!-- Loads and stores the permissions the user has -->
  {% has_permission user "read" project.id as user_has_read_permission %}
  {% has_permission user "add_users" project.id as user_has_add_users_permission %}
  {% has_permission user "create_tasks" project.id as user_has_create_tasks_permission %}
  {% has_permission user "modify_tasks" project.id as user_has_modify_tasks_permission %}
  {% has_permission user "delete_tasks" project.id as user_has_delete_tasks_permission %}
  {% has_permission user "modify_other_users_permissions" project.id as user_has_modify_other_users_permissions %}
  {% has_permission user "delete_users" project.id as user_has_delete_users_permission %}
  {% has_permission user "delete_project" project.id as user_has_delete_project_permission %}
  {% has_permission user "creator" project.id as user_has_creator_permission %}

  {% include "core/navbarlayout.html" %}
  {% include "core/sidebarlayout.html" with user_has_modify_other_users_permissions=user_has_modify_other_users_permissions user_has_delete_project_permission=user_has_delete_project_permission %}

  <section class="bg-dark-blue-2 text-light text-center text-sm-start p-5 p-lg-0 pt-lg-5" style="height: 100vh;">
    <div class="container py-5">
      <p>Task Name: {{ task.name }}</p>
      <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-primary">Update Status</button>
      </form>
    </div>
  </section>
{% endblock %}

core/templates/core/confirm_file_deletion.html
{% extends "main/layout.html" %}

{% block body %}
<section class="bg-dark-blue-2 text-light text-center text-sm-start p-5 p-lg-0 pt-lg-5" style="height: 100vh;">
  <div class="container pb-3">
      <h1>Confirm Deletion</h1>
      <h2>Files to be deleted:</h2>
      <ul>
          {% for file in files_to_delete %}
              <li>{{ file.file.name }}</li>
          {% endfor %}
      </ul>
      <form method="post">
          {% csrf_token %}
          <input type="hidden" name="confirm_delete_files" value="true">
          <button type="submit" class="btn btn-primary">Confirm Deletion</button>
          <a href="{% url 'core:modifytask' project.id task.id %}" class="btn btn-secondary">Cancel</a>
      </form>
  </div>
</section>
{% endblock %}

core/templates/core/myprojects.html
{% extends "main/layout.html" %}
{% load permissions_tags %}
{% load static %}

{% block title %}
  My Projects
{% endblock %}

{% load crispy_forms_tags %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}">
{% endblock %}

{% block body %}

  {% include "core/navbarlayout.html" %}

  <section class="bg-dark-blue-2 text-light text-center p-5 p-lg-0 pt-lg-5" style="height: 100vh;">
    <div class="container pb-3">
      <h1 class="display-4 fw-bold">Your Projects</h1>
    </div>
    <!-- Created Projects -->
    <div class="container">
      <p>Projects created by you:</p>
      {% for project in created_projects %}
        <div class="p-1">
          <a href="{% url 'core:project' project.id %}" class="btn btn-info btn-sm">
            <span class="fw-bold">
              {{ project.name }}
            </span>
          </a>
        </div>
      {% empty %}
        <p>No projects created</p>
      {% endfor %}
    </div>
    <!-- Joined Projects -->
    <div class="container p-4">
      <p>Projects you joined:</p>
      {% for project in joined_projects %}
        <div class="p-1">
          <a href="{% url 'core:project' project.id %}" class="btn btn-info btn-sm">
            <span class="fw-bold">
              {{ project.name }}
            </span>
          </a>
        </div>
      {% empty %}
        <p>No projects joined</p>
      {% endfor %}
    </div>
    <div class="pt-3">
      <a href="{% url 'core:addproject' %}" class="btn btn-success btn-lg">
        <span class="fw-bold">
          + Add Project
        </span>
      </a>
    </div>
  </section>
{% endblock %}

core/templates/core/navbarlayout.html
<!-- Navbar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark-blue-1 py-3 fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:home' %}">
        <span class="text-warning">
        TaskTrooper
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
        </span>
      </button>
      <div class="collapse navbar-collapse" id="navmenu">
        <ul class="navbar-nav justify-content-start">
          <li class="nav-item">
            <a href="{% url 'core:myprojects' %}" class="nav-link">View Projects</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto align-items-center justify-content-between">
          <li class="nav-item">
            <span class="text-warning">Hi, {{ user.first_name }}!</span>
          </li>
          <li class="nav-item">
            <a href="{% url 'socialaccount_connections' %}"" class="nav-link">My Socials</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_logout' %}" class="nav-link"><span class="btn btn-primary btn-sm">Logout</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

core/templates/core/project.html
{% extends "main/layout.html" %}

{% load permissions_tags %}

{% load static %}

{% block title %}
  {{ project.name }} 
{% endblock %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}">

  <!-- Marked: Move javascript to different file -->
  <script>
    function copyInviteLink() {
      const inviteLinkInput = document.getElementById("invite_code");
      const inviteCode = inviteLinkInput.value;
  
      // Construct the formatted invite link
      const websiteURL = window.location.origin;
      const formattedLink = `${websiteURL}/app/myprojects/${inviteCode}/join`;
  
      // Create a temporary input element to copy the formatted link to the clipboard
      const tempInput = document.createElement("input");
      tempInput.value = formattedLink;
      document.body.appendChild(tempInput);
      tempInput.select();
      document.execCommand("copy");
      document.body.removeChild(tempInput);
  
      // Alert the current user that the invite link has been copied to the clipboard
      alert("Invite link copied to clipboard: " + formattedLink);
    }
  </script>
{% endblock %}

{% block body %}

  <!-- Loads and stores the permissions the user has -->
  {% has_permission user "read" project.id as user_has_read_permission %}
  {% has_permission user "add_users" project.id as user_has_add_users_permission %}
  {% has_permission user "create_tasks" project.id as user_has_create_tasks_permission %}
  {% has_permission user "modify_tasks" project.id as user_has_modify_tasks_permission %}
  {% has_permission user "delete_tasks" project.id as user_has_delete_tasks_permission %}
  {% has_permission user "modify_other_users_permissions" project.id as user_has_modify_other_users_permissions %}
  {% has_permission user "delete_users" project.id as user_has_delete_users_permission %}
  {% has_permission user "delete_project" project.id as user_has_delete_project_permission %}
  {% has_permission user "creator" project.id as user_has_creator_permission %}

  {% include "core/navbarlayout.html" %}
  {% include "core/sidebarlayout.html" with user_has_modify_other_users_permissions=user_has_modify_other_users_permissions user_has_delete_project_permission=user_has_delete_project_permission %}

  <section class="bg-dark-blue-2 text-light text-center p-5 p-lg-0 pt-lg-5" style="min-height: 100vh;">
    <div class="container pb-3">
        <h1 class="display-4 fw-bold">Project Name: {{ project.name }}</h1>
        <div class="text-start">
          <p>Click on the task's name to view it's description.</p>
        </div>
    </div>
    <div class="container">
      <table class="table text-light" data-toggle="table">
        {% if tasks %}
          <thead>
            <tr>
              <th scope="col">id</th>
              <th scope="col">Name of Task</th>
              <th scope="col">Assigned Users</th>
              <th data-sortable="true" scope="col">Start Date & Time</th>
              <th data-sortable="true" scope="col">End Date & Time</th>
              <th scope="col">Files</th>
              <th data-sortable="true" scope="col">Status</th>
              {% if user_has_modify_tasks_permission %}
                <th scope="col">Actions</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for task in tasks %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'core:taskproperties' project.id task.id %}" class="nav-link">{{ task.name }}</a></td>
                <td>
                  {% for user in task.users.all %}
                    <div>{{ user.username }}</div>
                  {% endfor %}
                </td>
                <td>{{ task.start_datetime }}</td>
                <td>{{ task.end_datetime }}</td>
                <td>
                  {% if not task.task_files.all %}
                    -
                  {% else %}
                    {% for file in task.task_files.all %}
                      <a href="{{ file.file.url }}" target="_blank">{{ file.file.name|cut:"files/" }}</a><br>
                    {% endfor %}
                  {% endif %}
                </td>
                <td class="{% if task.status == 'Not yet started' %}status-not-started{% elif task.status == 'In-process' %}status-in-process{% elif task.status == 'Completed' %}status-completed{% endif %}">{{ task.status }}</td>
                {% if user_has_modify_tasks_permission %}
                  <td>
                    {% if user_has_delete_tasks_permission %}
                      <a href="{% url 'core:deletetask' project.id task.id %}" class="nav-link p-1"><span class="btn btn-danger btn-sm">Delete</span></a>
                    {% endif %}
                    {% if user_has_modify_tasks_permission %}
                      <a href="{% url 'core:changetaskstatus' project.id task.id %}" class="nav-link p-1"><span class="btn btn-info btn-sm">Change Status</span></a>
                      <a href="{% url 'core:modifytask' project.id task.id %}" class="nav-link p-1"><span class="btn btn-info btn-sm">Modify Task</span></a>
                    {% endif %}
                  </td>
                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
        {% else %}
          <tr>
            <td colspan="6">No tasks found.</td>
          </tr>
        {% endif %}
      </table>
    </div>
    {% if user_has_create_tasks_permission %}
      <div class="pt-5">
        <a href="{% url 'core:addtask' project.id %}" class="btn btn-success btn-lg">
          <span class="fw-bold">
            + Add Task
          </span>
        </a>
      </div>
    {% endif %}
    {% if user_has_add_users_permission %}
      <form>
        <div class="form-group pt-5 pb-3">
            <label for="invite_code">Invite Code:</label>
            <input type="text" id="invite_code" name="invite_code" value="{{ project.invite_code }}" readonly>
        </div>
        <button type="submit" class="btn btn-info btn-sm" onclick="copyInviteLink()">Copy Invite Link</button>
      </form>
    {% endif %}

  </section>
{% endblock %}

core/templates/core/projectmanagement.html
{% extends "main/layout.html" %}
{% load permissions_tags %}
{% load static %}

{% block title %}
  {{ project.name }} 
{% endblock %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}">
{% endblock %}

{% block body %}
  
  <!-- Loads and stores the permissions the user has -->
  {% has_permission user "read" project.id as user_has_read_permission %}
  {% has_permission user "add_users" project.id as user_has_add_users_permission %}
  {% has_permission user "create_tasks" project.id as user_has_create_tasks_permission %}
  {% has_permission user "modify_tasks" project.id as user_has_modify_tasks_permission %}
  {% has_permission user "delete_tasks" project.id as user_has_delete_tasks_permission %}
  {% has_permission user "modify_other_users_permissions" project.id as user_has_modify_other_users_permissions %}
  {% has_permission user "delete_users" project.id as user_has_delete_users_permission %}
  {% has_permission user "delete_project" project.id as user_has_delete_project_permission %}
  {% has_permission user "creator" project.id as user_has_creator_permission %}

  {% include "core/navbarlayout.html" %}
  {% include "core/sidebarlayout.html" with user_has_modify_other_users_permissions=user_has_modify_other_users_permissions user_has_delete_project_permission=user_has_delete_project_permission %}

  <section class="bg-dark-blue-2 text-light text-center p-5 p-lg-0 pt-lg-5">
    <div class="container pb-3">
      <h1>Project Management</h1>
    </div>
  </section>

  <section class="bg-dark-blue-2 text-light text-center p-5 p-lg-0 pt-lg-5" style="height: 100vh;">
    <div class="container pb-3">
        <form method="POST" action="{% url 'core:updateprojectname' project.id %}">
            {% csrf_token %}
            <label for="id_project_name">Project Name:</label>
            <input type="text" name="project_name" id="id_project_name" value="{{ project.name }}">
            <button type="submit">Update Project Name</button>
        </form>
    </div>
    {% if user_has_delete_project_permission %}
      <div class="container pt-3 pb-3">
        <a href="{% url 'core:deleteproject' project.id %}" class="nav-link"><span class="btn btn-danger btn-sm">Delete Project?</span></a>
      </div>
    {% endif %}
  </section>

  
{% endblock %}

core/templates/core/sidebarlayout.html
<!-- Sidebar -->
<div class="sidebar">
    <a href="{% url 'core:project' project.id %}">Project Home</a>
    <a href="{% url 'core:edituserprofile' project.id %}">Profile</a>
    <a href="{% url 'core:allusers' project.id %}">All Users</a>
    {% if user_has_modify_other_users_permissions %}
      <a href="{% url 'core:user_management' project.id %}">User Management</a>
    {% endif %}
    {% if user_has_delete_project_permission %}
      <a href="{% url 'core:project_management' project.id %}">Project Management</a>
    {% endif %}
</div>