TaskTrooper/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('app/', include('core.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='home'),
    path('myprojects/', views.myprojects, name='myprojects'), # Overview of all projects
    path('myprojects/addproject', views.addproject, name='addproject'), # Add a project
    path('myprojects/<int:project_id>/', views.project, name='project'), # Overview of a project
    path('myprojects/<int:project_id>/deleteproject', views.deleteproject, name='deleteproject'), # Delete a project
    path('myprojects/<int:project_id>/usermanagement/', views.user_management, name='user_management'), # Bulk modify users' permissions
    path('myprojects/<int:project_id>/projectmanagement/', views.project_management, name='project_management'), # Manage a project
    path('myprojects/<int:project_id>/updateprojectname/', views.update_project_name, name='updateprojectname'),
    path('myprojects/<int:project_id>/edituserprofile/', views.edit_user_profile, name='edituserprofile'),
    path('myprojects/<int:project_id>/allusers/', views.allusers, name='allusers'),
    path('myprojects/<str:invite_code>/join', views.joinproject, name='joinproject'), # Join a project
    path('myprojects/<int:project_id>/addtask', views.addtask, name='addtask'), # Add a task
    path('myprojects/<int:project_id>/<int:task_id>/', views.taskproperties, name='taskproperties'), # Overview of a task
    path('myprojects/<int:project_id>/<int:task_id>/deletetask', views.deletetask, name='deletetask'), # Delete a task
    path('myprojects/<int:project_id>/<int:task_id>/changetaskstatus', views.changetaskstatus, name='changetaskstatus'), # Change a task's status
    path('myprojects/<int:project_id>/<int:task_id>/modifytask', views.modifytask, name='modifytask') # Change a task's status
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path("", views.index, name="home"),
]

main/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return render(request, "main/index.html")
    return render(request, "main/index.html")

main/templates/main/index.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}
  TaskTrooper
{% endblock %}

{% block body %}
  <!-- Navbar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark-blue-1 py-3 fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'main:home' %}"><span class="text-warning">
        TaskTrooper
      </span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navmenu">
        {% if user.is_authenticated %}
          <ul class="navbar-nav justify-content-start">
            <li class="nav-item">
              <a href="{% url 'core:myprojects' %}" class="nav-link">View Projects</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto align-items-center justify-content-between">
            <li class="nav-item">
              <span class="text-warning">Hi, {{ user.first_name }}!</span>
            </li>
            <li class="nav-item">
              <a href="{% url 'account_logout' %}" class="nav-link"><span class="btn btn-primary btn-sm">Logout</span></a>
            </li>
          </ul>
        {% else %}
          <ul class="navbar-nav ms-auto align-items-center justify-content-between">
            <li class="nav-item">
              <a href="#about" class="nav-link">About</a>
            </li>
            <li class="nav-item">
              <a href="#contactus" class="nav-link">Contact Us</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account_login' %}" class="nav-link"><span class="btn btn-primary btn-sm">Login</span></a>
            </li>
          </ul>
        {% endif %}
      </div>
    </div>
  </nav>

  <!-- Welcome -->
  <section class="bg-dark-blue-2 text-light text-center text-sm-start p-5 p-lg-0 pt-lg-5">
    <div class="container">
      <div class="d-sm-flex align-items-center justify-content-between">
        <div>
          <h1>
            Welcome to
            <span class="text-warning">TaskTrooper</span>
          </h1>
          <p class="lead">
            A simple project management app
          </p>
          <a href="{% url 'account_signup' %}">
            {% if not user.is_authenticated %}
              <button class="btn btn-primary btn-lg">
                Sign Up Now!
              </button>
            {% else %}
            {% endif %}
          </a>
        </div>
        <img class="img-fluid w-50 d-none d-sm-block" src="{% static 'main/img/undraw_scrum_board_re_wk7v.svg' %}" alt="Task Trooper Logo">
      </div>
    </div>
  </section>

  <!-- Cards -->
  <section class="bg-vibrant-blue text-light text-center p-5">
    <div class="container">
      <h1 class="pb-5">
        What can you do?
      </h1>
      <div class="row row-cols-lg-4 row-cols-md-2 row-cols-1 g-2">
        <!-- Card 1 -->
        <div class="col">
          <div class="card h-100 bg-yellow-green text-vibrant-blue">
            <img class="card-img-top img-fluid d-none d-md-block" src="{% static 'main/img/undraw_add_tasks_re_s5yj.svg' %}" alt="Add Tasks">
            <div class="card-body">
              <p class="card-text">
                <div class="card-text-font">
                  Create new projects
                </div>
              </p>
            </div>
          </div>
        </div>
        <!-- Card 2 -->
        <div class="col">
          <div class="card h-100 bg-yellow-green text-vibrant-blue">
            <img class="card-img-top img-fluid d-none d-md-block" src="{% static 'main/img/undraw_progress_overview_re_tvcl.svg' %}" alt="Manage Tasks">
            <div class="card-body">
              <p class="card-text">
                <div class="card-text-font">
                  Manage a project
                </div>
              </p>
            </div>
          </div>
        </div>
        <!-- Card 3 -->
        <div class="col">
          <div class="card h-100 bg-yellow-green text-vibrant-blue">
            <img class="card-img-top img-fluid d-none d-md-block" src="{% static 'main/img/undraw_collaboration_re_vyau.svg' %}" alt="Lead Team">
            <div class="card-body">
              <p class="card-text">
                <div class="card-text-font">
                  Lead a team
                </div>
              </p>
            </div>
          </div>
        </div>
        <!-- Card 4 -->
        <div class="col">
          <div class="card h-100 bg-yellow-green text-vibrant-blue">
            <img class="card-img-top img-fluid d-none d-md-block" src="{% static 'main/img/undraw_project_completed_re_jr7u.svg' %}" alt="Track Tasks">
            <div class="card-body">
              <p class="card-text">
                <div class="card-text-font">
                  Track assigned tasks
                </div>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- How we help -->
  <section class="bg-dark-blue-2 text-light text-center text-sm-end p-5 p-lg-0 pt-lg-5">
    <div class="container">
      <div class="d-sm-flex align-items-center justify-content-between">
        <img class="img-fluid w-50 d-none d-sm-block" src="{% static 'main/img/undraw_group_chat_re_frmo.svg' %}" alt="Add Tasks">
        <div>
          <h1 class="pb-3">
            How we help?
          </h1>
          <div class="lead"> 
            <p> 
              Sometimes, it's hard to keep track of all the tasks that need to be done.
              Communication between team members may not be the best.
              We help to streamline project management, improve collaboration and provide real-time updates.
            </p>
            <p>
              This way, you can focus on what matters most.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="{% static 'main/styles.css' %}" rel="stylesheet">
    <script
      src="https://code.jquery.com/jquery-3.7.0.min.js"
      integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
      crossorigin="anonymous">
    </script>
    
    {% block head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
    {% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.js"></script>
  </body>
</html>